name: Claude Code CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  claude-code-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        cache: true
        
    - name: Setup Node.js for Claude Code
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Flutter dependencies
      run: flutter pub get
      
    - name: Run Flutter analyzer
      run: flutter analyze
      
    - name: Install Claude Code CLI
      run: npm install -g @anthropic-ai/claude-code
      
    - name: Run Claude Code analysis
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        CLAUDE_CODE_MODEL: claude-4-20250514
      run: |
        claude-code --version
        # Flutter アプリ開発に特化した自律的開発タスク
        claude -p "CLAUDE.mdのFlutterアプリ仕様書を読んで、現在のプロジェクト状況を分析し、次にやるべき開発タスクを優先順位付きで提案して"
        claude -p "Dart/Flutterのベストプラクティスに基づいてコード品質をチェックし、改善提案をして"
        claude -p "Flutterアプリのパフォーマンス（60fps維持、起動時間最適化）をチェックして"
        claude -p "Material Design 3に準拠したUI/UX改善提案をして"
        claude -p "モバイルアプリのセキュリティベストプラクティスに沿ってチェックして"
        claude -p "ユニットテスト、ウィジェットテスト、統合テストの戦略を提案して"
        
    - name: Run Flutter tests
      run: flutter test
      continue-on-error: true
        
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: claude-code-results
        path: |
          *.log
          reports/